name: app_flutter_biometry_access
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.8
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.10
  go_router: ^14.8.1
  google_fonts: ^6.3.0
  heroicons: ^0.11.0
  http: ^1.4.0
  intl: ^0.20.2
  provider: ^6.1.5
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo_app.png
    - assets/images/background.png

flutter_icons:
  android: true
  image_path: "assets/icons/logo_app.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF" # Fondo blanco
  image: "assets/icons/logo_app.png" # Imagen principal centrada
  # background_image: "assets/images/background.png"  # Imagen de fondo (opcional)
  # branding: "assets/branding.png"  # Imagen secundaria en la parte inferior (opcional)
  fullscreen: true
